[package]
name = "ray"
version = "0.1.0"
authors = ["Miles Watson"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
piston_window = "0.130.0"
pbr = "1"
rayon = "1"
alea = "0.2.2"
