[package]
name = "raytracing"
version = "0.1.0"
authors = ["Miles Watson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21.1"
piston_window = "0.93.0"
pbr = "1.0.4"
rayon="1.5.0"
