[package]
name = "ray"
version = "0.1.0"
authors = ["Miles Watson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.0"
piston_window = "0.120.0"
pbr = "1.0.4"
rayon = "1.5.1"
alea = "0.2.2"